[package]
name = "websockets_server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = {version = "1.38.1", features = ["rt", "rt-multi-thread", "macros"]}
warp = {version = "0.3.7", features = ["tls"]}
futures = "*"